#ifndef _BBRLIBSTDC_DEPEND_BASE_H_
#define _BBRLIBSTDC_DEPEND_BASE_H_

#define _BBRLIBSTDC_CHAR_BIT 8
#define _BBRLIBSTDC_CHAR_SIGNED 1
#define _BBRLIBSTDC_SHORT_BIT 16
#define _BBRLIBSTDC_INT_BIT 32
#define _BBRLIBSTDC_LONG_BIT 64
#define _BBRLIBSTDC_LLONG_BIT 64

#endif /* _BBRLIBSTDC_DEPEND_BASE_H_ */
